["Magnavox Odyssey",
"Ping-O-Tronic",
"VideoSport MK2",
"PC-50X",
"Video-2000",
"Tele-Spiel",
"Coleco Telstar",
"APF TV Fun",
"OC-4",
"Odyssey 2100",
"Pong",
"Super Pong",
"Radio Shack TV Scoreboard",
"Stunt Cycle",
"Video Pinball",
"Ultra Pong Doubles",
"Atari Game Brain",
"Philips N20",
"Color TV-Game 6",
"Telescore 750",
"Hanimex TVG 8610",
"Color TV Game 15",
"Color TV Game Racing 112",
"Color TV Game Block Kuzushi",
"Telescore 752",
"Computer TV Game",
"BSS 01",
"Fairchild Channel F",
"Video Entertainment System",
"1292 Advanced Programmable Video System",
"Hanimex TVG 070C",
"Channel F System II",
"Hanimex SD-070 Couleur",
"RCA Studio II",
"Atari 2600",
"Atari 2600 Jr.",
"Atari 2800",
"Coleco Gemini",
"Bally Astrocade",
"Interton VC 2400",
"Interton VC 2501",
"Interton VC4000",
"Magnavox Odyssey²",
"Magnavox Odyssey 3",
"APF Imagination Machine",
"Game and Watch",
"Intellivision",
"Bandai Super Vision 8000",
"Intellivision II",
"CreatiVision",
"Epoch Cassette Vision",
"Emerson Arcadia 2001",
"Atari 5200",
"Atari 5100",
"ColecoVision",
"Entex Adventure Vision",
"Vectrex",
"Compact Vision TV-Boy",
"My Vision",
"Pyuuta Jr.",
"MicroVision",
"Gameoff",
"TeleTenis",
"Alf2",
"Super Cassette Vision",
"Halcyon",
"Intellivision III",
"PV-1000",
"Commodore 64GS",
"GX-4000",
"Atari 7800",
"Atari XEGS",
"Sega SG-1000",
"Sega SG-1000 II",
"Master System, Sega Mark III",
"Master System II",
"Master System III",
"Nintendo Entertainment System",
"C1 NES TV",
"Famicom Disk System",
"Zemmix",
"BBC Bridge Companion",
"VideoSmarts",
"Action Max",
"Video Challenger",
"Video Art",
"Famicom AV",
"Mega Drive",
"Mega Drive II",
"Sega Genesis II",
"Mega Drive III",
"Sega Genesis 3",
"Game Gear",
"Mega-CD/Sega CD",
"Sega 32X",
"JVC X'eye",
"Sega Pico",
"Sega Mega Jet",
"Atari Lynx",
"Atari Lynx II",
"PC Engine",
"TurboGrafx-CD",
"SuperGrafX",
"PC-Engine LT",
"Turbo Express",
"View-Master Interactive Vision",
"VTech Socrates",
"Terebikko",
"Konix Multisystem",
"Neo-Geo",
"Neo-Geo CD",
"Neo-Geo CDZ",
"Commodore CDTV",
"Memorex VIS",
"Game Boy",
"Super Nintendo",
"SF-1 SNES TV",
"SNES",
"SNES-CD",
"Satellaview",
"Game Boy Pocket",
"Game Boy Light",
"CD-i",
"TurboDuo",
"Watara Supervision",
"Sega Nomad",
"Pioneer LaserActive",
"Super A'Can",
"PC Engine Shuttle",
"CoreGraphX",
"CoreGraphX II",
"PC Engine Duo-R",
"PC Engine Duo-RX",
"PC-KD863G Monitor",
"Virtual Boy",
"FM Towns Marty",
"Apple Pippin",
"R-Zone",
"Game.com",
"PC-FX",
"Atari Jaguar",
"Atari Jaguar CD",
"Atari Jaguar II",
"PlayStation",
"Net Yaroze",
"PocketStation",
"PSone",
"Sega Saturn",
"Panasonic M2",
"3DO Interactive Multiplayer",
"Amiga CD32",
"Casio Loopy",
"Playdia",
"CP System Changer",
"Game Boy Color",
"Nintendo 64",
"Nintendo 64DD",
"Sega Neptune",
"Neo-Geo Pocket",
"Sega Pluto",
"Neo-Geo Pocket Color",
"WonderSwan Color",
"SwanCrystal",
"ApeXtreme",
"Atari Flashback",
"Dreamcast",
"Advanced Pico Beena",
"L600",
"Nintendo GameCube",
"Nuon",
"IQue Player",
"Panasonic Q",
"PlayStation 2",
"PlayStation 2 Slim",
"PSX",
"GP32",
"N-Gage",
"N-Gage QD",
"V.Smile",
"Zodiac",
"XaviXPort gaming console",
"GameKing",
"Xbox",
"Pokémon Mini",
"Game Boy Advance",
"Game Boy Advance SP",
"Game Boy Micro",
"Leapster TV",
"GoGo TV Video Vision",
"Buzztime Home Trivia System",
"Atari Flashback 2",
"Atari Flashback 3",
"Atari Flashback 4",
"Gizmondo",
"V.Smile Pro",
"V.Smile Pocket",
"V.Smile Baby",
"V.Flash",
"V.Smile V.Motion",
"G-SPHERE",
"Generation NEX",
"DigiBLAST",
"FC Twin Video Game System",
"EVO Smart Console",
"Retro Duo",
"Leapster",
"GameSystem",
"Game Wave",
"Pandora",
"Mattel HyperScan",
"ION",
"OnLive",
"Phantom",
"PlayStation 3",
"PlayStation 3 Slim",
"PlayStation 3 Ultra Slim",
"PlayStation Portable",
"PSP Slim & Lite",
"PSP 3000",
"PSP Go",
"PSP Street",
"Wii",
"Wii Mini",
"Nintendo DS",
"Nintendo DS Lite",
"Nintendo DSi",
"Nintendo DSi XL",
"Xbox 360",
"Xbox 360 Slim",
"GP2X",
"XGP",
"GP2X Wiz",
"GP2X Caanoo",
"Zeebo",
"Zone",
"Clickstart My First Computer",
"Zippity",
"VMIGO TV",
"Telestory",
"Smart Cycle",
"Mega Drive 4",
"PlayStation Vita",
"Nintendo 3DS",
"Nintendo 3DS XL",
"Wii U",
"Nintendo 2DS",
"Nvidia Shield",
"GameStick",
"Ouya",
"PlayStation 4",
"PlayStation TV",
"Xbox One",
"Piston",
"Pandora TV-Box",
"G-cluster",
"MOJO",
"flarePlay",
"Xtreamer Multi-Console",
"FunBox",
"Fire TV",
"Fire TV Stick",
"T2",
"Tron",
"Shadow Stick 3",
"X18",
"LeapTV",
"TIMEBOX",
"Nexus Player",
"G-BOX",
"New Nintendo 3DS",
"New Nintendo 3DS XL",
"Atari Flashback 5",
"Atari Flashback 6",
"Steam Machine",
"Nvidia Shield TV",
"Playdroid TV",
"Atari Flashback 7",
"Coleco Chameleon",
"GPD Win",
"Xbox One S",
"PlayStation 4 Slim",
"PlayStation 4 Pro",
"New Nintendo 2DS XL",
"Nintendo Switch",
"Xbox One X",
"Google Stadia",
"Nvidia Tv Pro",
"Nintendo Switch Lite",
"Nintendo Switch Oled",
"PlayStation 5",
"PlayStation 5 Digital",
"Xbox Series X",
"Xbox Series S",
"Atari VCS",
"GeForce Now",
"Polymega",
"Playdate",
"Steam Deck",
"Amazon Luna",
"ASUS ROG Ally",
]
